---
- name: Initial Setup
  gather_facts: true
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Install RPM Fusion free
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install git
      become: true
      dnf:
        name: git
        state: present

    - name: Install telegram-desktop
      become: true
      dnf:
        name: telegram-desktop
        state: present

    - name: Install syncthing
      become: true
      dnf: 
        name: syncthing
        state: present

#figure out how to enable syncthing programatically

    - name: Install wine
      become: true
      dnf:
        name: wine, wine.i686
        state: present

    - name: Install lutris
      become: true
      dnf:
        name: lutris
        state: present

    - name: Install darktable
      become: true
      dnf: 
        name: darktable
        state: present

    - name: Create software dir
      file:
        path: /home/kiretza/Software
        state: directory
        mode: "755"
    
    - name: Copy keepassxc to the Software dir
      copy:
        src: ./Keepass.AppImage
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Create applications directory in .local/share
      file:
        path: /home/kiretza/.local/share/applications
        mode: "755"

    - name: Copy keepass desktop file to .local.share
      copy:
        src: ./keepassxc.desktop
        dest: /home/kiretza/.local/share/applications
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get the joplin appimage
      get_url:
        url: "https://github.com/laurent22/joplin/releases/download/v3.1.24/Joplin-3.1.24.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get simpleX appimage
      get_url:
        url: "https://github.com/simplex-chat/simplex-chat/releases/latest/download/simplex-desktop-x86_64.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

