---
- name: Initial Setup
  gather_facts: true
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Install RPM Fusion free
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install applications
      become: true
      dnf:
        name: git, vim, telegram-desktop, syncthing, wine, wine.i686, lutris, darktable, deluge, fastfetch, wireguard-tools, podman, podman-compose
        state: present

    - name: Install Visual Studio Code
      become: true
      dnf:
        name: "https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64"
        state: present

    - name: Copy systemd file for syncthing
      become: true
      copy:
        src: ./syncthing@.service
        desk: /etc/systemd/system/syncthing@.service
        mode: "751"

    - name: Enable systemd service for syncthing
      become: true
      systemd_service:
        name: syncthing@kiretza.service
        enabled: true
        state: started

    - name: Create software dir
      file:
        path: /home/kiretza/Software
        state: directory
        mode: "755"
    
    - name: Copy keepassxc to the Software dir
      copy:
        src: ./Keepass.AppImage
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Create applications directory in .local/share
      file:
        path: /home/kiretza/.local/share/applications
        mode: "755"

    - name: Copy keepass desktop file to .local.share
      copy:
        src: ./keepassxc.desktop
        dest: /home/kiretza/.local/share/applications
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get the joplin appimage
      get_url:
        url: "https://github.com/laurent22/joplin/releases/download/v3.1.24/Joplin-3.1.24.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get simpleX appimage
      get_url:
        url: "https://github.com/simplex-chat/simplex-chat/releases/latest/download/simplex-desktop-x86_64.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Setup wireguard
      become: true
      copy:
        src: ./wg2.conf
        dest: /etc/wireguard/wg1.conf

    - name: Import wireguard connection to nmcli
      become: true
      shell: nmcli connection import type wireguard file /etc/wireguard/wg1.conf

    