---
- name: Initial Setup
  gather_facts: true
  hosts: localhost
  connection: local
  become_user: root
  tasks:
    - name: Install RPM Fusion free
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: True

    - name: Install RPM Fusion non-free
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: True

    - name: Install git, vim
      become: true
      dnf:
        name: git, vim
        state: present

    - name: Install syncthing, deluge, fastfetch
      become: true
      dnf: 
        name: syncthing, deluge, fastfetch
        state: present

    - name: Install wine, lutris, steam
      become: true
      dnf:
        name: wine, wine.i686, lutris, steam
        state: present
    
    - name: Install darktable
      become: true
      dnf:
        name: darktable
        state: present

    - name: Install podman, podman-compose
      become: true
      dnf:
        name: podman, podman-compose
        state: present
      
    
    - name: Install rclone
      become: true
      dnf:
        name: rclone
        state: present

    - name: Upgrade rclone
      become: true
      shell: rclone self-update

    - name: Install VS code
      become: true
      dnf:
        name: "https://vscode.download.prss.microsoft.com/dbazure/download/stable/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/code-1.96.2-1734607808.el8.x86_64.rpm"
        state: present
    
    - name: Copy systemd file for syncthing
      become: true
      copy:
        src: ./syncthing@.service
        dest: /etc/systemd/system/syncthing@.service
        mode: "751"

    - name: Enable systemd service for syncthing
      become: true
      systemd_service:
        name: syncthing@kiretza.service
        enabled: true
        state: started

    - name: Install qemu and virt-manager
      become: true
      dnf:
        name: qemu-kvm, virt-manager
        state: present

    - name: Create software dir
      file:
        path: /home/kiretza/Software
        state: directory
        mode: "755"
    
    - name: Copy keepassxc to the Software dir
      copy:
        src: ./KeePassXC-2.7.6-x86_64.AppImage
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"
    
    - name: Copy Keepass icon to Software
      copy:
        src: ./keepassxc.svg
        dest: /home/kiretza/Software/keepassxc.svg
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Create applications directory in .local/share
      file:
        path: /home/kiretza/.local/share/applications
        state: directory
        mode: "755"


    - name: Copy keepass desktop file to .local.share
      copy:
        src: ./keepassxc.desktop
        dest: /home/kiretza/.local/share/applications
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get the joplin appimage
      get_url:
        url: "https://github.com/laurent22/joplin/releases/download/v3.1.24/Joplin-3.1.24.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Copy joplin destop file 
      copy:
        src: ./joplin.desktop
        dest: /home/kiretza/.local/share/applications
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Copy joplin icon to Software
      copy:
        src: ./joplin-icon.png
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"

    - name: Get simpleX appimage
      get_url:
        url: "https://github.com/simplex-chat/simplex-chat/releases/latest/download/simplex-desktop-x86_64.AppImage"
        dest: /home/kiretza/Software
        owner: kiretza
        group: kiretza
        mode: "755"



    
